Added the Geolocation (current location of user) Feature
OneBusAway/onebusaway-webapp pull request #16
Opened 2024-07-05 15:32 UTC by tarunsinghofficial

Fixed #4 

**Tasks done**:

- Added a 'Find Current Location' button to the map.
- Clicking the button first gets the user permission, and if allowed we center the map with their current location.

**Screenshot:**
![bandicam2024-07-0520-55-03-272-ezgif com-video-to-gif-converter](https://github.com/OneBusAway/onebusaway-webapp/assets/62840625/1bca8037-0e87-43be-a6d5-e33d9fbcb2f4)

2024-07-05 17:00 UTC, aaronbrethorst requested changes
The feature works great! I noted some code changes I'd like to see before merging. Please let me know via slack if you have any questions!

2024-07-05 17:00 UTC, aaronbrethorst commented on src/components/map/GoogleMap.svelte
> +		const locationButton = document.createElement('button');
I'd love to see this extracted out into a reusable component. We'll want to support different map backends at some point (Mapbox, OSM, Bing, Apple, etc.), and I want to make sure that we can reuse as much functionality across them as possible. 

Once it's a reusable component, it should be straightforward (I hope) to use the Font Awesome package to display the crosshairs icon instead of loading the entire package from a CDN.

2024-07-05 17:00 UTC, aaronbrethorst commented on src/components/map/GoogleMap.svelte
> +			if (navigator.geolocation) {
Stylistically, I prefer early returns over deep nesting. it makes it easier to read your code and follow the control flow. What I mean by this here is to flip your conditions around:

```
if (!navigator.geolocation) {
  alert('Geolocation is not supported by this browser.');
  return;
}

// ... continue on with the rest of your logic.
```

2024-07-05 17:00 UTC, aaronbrethorst commented on src/components/map/GoogleMap.svelte
> +						new google.maps.Marker({
since we want the button to be a reusable component, can you keep this marker logic here and invoke it with a callback from the LocationButton component?

2024-07-05 17:00 UTC, aaronbrethorst commented on src/components/map/GoogleMap.svelte
> +<link
make sure to remove this after making the other changes!

2024-07-06 08:30 UTC, tarunsinghofficial commented on src/components/map/GoogleMap.svelte
> +			if (navigator.geolocation) {
Sure, that's a great approach. I have added the early return statement.

2024-07-06 08:31 UTC, tarunsinghofficial commented on src/components/map/GoogleMap.svelte
> +		const locationButton = document.createElement('button');
Okay. I will make sure to create a reusable component for using in the future.

2024-07-06 08:34 UTC, tarunsinghofficial commented on src/components/map/GoogleMap.svelte
> +						new google.maps.Marker({
Done this one.

2024-07-06 15:23 UTC, aaronbrethorst approved these changes
awesome, great work! 👏

2024-07-06 15:23 UTC, merged